#Author: John Ayres ############################################################
#tags:ML,Regression,Model Selections
#Desc: This script takes generates several linear regressions, using forward,
#      backwards and hybrid searches.Search stopping using AIC/BIC, k-fold  
#      analysis and CV error preformed using ML techniques(With set seed for 
#      reproducibility) it then compares the model calles for each method. 

library(boot)
library(MPV)
library(MASS)
library(leaps)
library(MASS)
library(qpcR)
library(caret)
pdf(file="HW11_RegMeth_OUT.pdf")

boston=read.table("boston.txt",header=T,sep="\t")

#Forward Search ################################################################
model.for<-regsubsets(CMEDV~CRIM+ZN+INDUS+CHAS+NOX+RM+AGE+DIS+RAD+TAX+PTRATIO+B
                      +LSTAT,method="forward",data=boston)
model.for.s<-summary(model.for)
model.for.s$which

# model ordering: Intercept, LSTAT, RM, PTRATIO, DIS, NOX, CHAS, B, ZN
# EXCLUDED: CRIM, INDUS, AGE, RAD, TAX

plot(model.for.s$bic)
plot(model.for.s$adjr2)
#Best model is the full forward model as seen in line 8
#Intercept, LSTAT, RM, PTRATIO, DIS, NOX, CHAS, B, ZN

#Forward search stop for BIC ###################################################

full=lm(CMEDV~CRIM+ZN+INDUS+CHAS+NOX+RM+AGE+DIS+RAD+TAX+PTRATIO+B+LSTAT,data=boston)
out.forward=step(full,k=log(506),direction="forward",Data=boston,trace=FALSE)
out.forward$coefficients
out.forward$anova
#If we stop the forward model based on BIC we end with 11 variables. 
#Intercept, LSTAT, RM, PTRATIO, DIS, NOX, CHAS, B, ZN, CRIM, RAD, TAX 

#Backward search ###############################################################
model.bac<-regsubsets(CMEDV~CRIM+ZN+INDUS+CHAS+NOX+RM+AGE+DIS+RAD+TAX+PTRATIO+B
                      +LSTAT,method="backward",data=boston,nvmax=15)
model.bac.s<-summary(model.bac)
model.bac.s$which

plot(model.bac.s$bic)

#Backwards search stop for BIC #################################################
out.bac=step(full,k=log(506),direction="backward",data=boston,trace=FALSE)
out.bac$coefficients
out.bac$anova

# Creating models for PRESS, call and plotting of press for models generated by 
# backwards search##############################################################
m1<-lm(CMEDV~LSTAT,data=boston)
m2<-lm(CMEDV~RM+LSTAT,data=boston)
m3<-lm(CMEDV~RM+PTRATIO+LSTAT,data=boston)
m4<-lm(CMEDV~RM+DIS+PTRATIO+LSTAT,data=boston)
m5<-lm(CMEDV~NOX+RM+DIS+PTRATIO+LSTAT,data=boston)
m6<-lm(CMEDV~NOX+RM+DIS+PTRATIO+B+LSTAT,data=boston)
m7<-lm(CMEDV~NOX+RM+DIS+RAD+PTRATIO+B+LSTAT,data=boston)
m8<-lm(CMEDV~NOX+RM+DIS+RAD+TAX+PTRATIO+B+LSTAT,data=boston)
m9<-lm(CMEDV~ZN+NOX+RM+DIS+RAD+TAX+PTRATIO+B+LSTAT,data=boston)
m10<-lm(CMEDV~CRIM+ZN+NOX+RM+DIS+RAD+TAX+PTRATIO+B+LSTAT,data=boston)
m11<-lm(CMEDV~CRIM+ZN+CHAS+NOX+RM+DIS+RAD+TAX+PTRATIO+B+LSTAT,data=boston)
m12<-lm(CMEDV~CRIM+ZN+INDUS+CHAS+NOX+RM+DIS+RAD+TAX+PTRATIO+B+LSTAT,data=boston)
m13<-lm(CMEDV~CRIM+ZN+INDUS+CHAS+NOX+RM+AGE+DIS+RAD+TAX+PTRATIO+B+LSTAT,data=boston)

press<-c(PRESS(m1),PRESS(m2),PRESS(m3),PRESS(m4),PRESS(m5),PRESS(m6),PRESS(m7),
         PRESS(m8),PRESS(m9),PRESS(m10),PRESS(m11),PRESS(m12),PRESS(m13))

plot(press)

#Setting up and running of ML modeling using k-fold validation(backwards selection)
set.seed(123)
train.Control<-trainControl(method="cv",number=10)
model.bac.MLfold<-train(CMEDV~CRIM+ZN+INDUS+CHAS+NOX+RM+AGE+DIS+RAD+TAX+PTRATIO
                        +B+LSTAT,data=boston,method="leapBackward",
                        tuneGrid=data.frame(nvmax=1:13),trControl=train.Control)

model.bac.MLfold$results
plot(model.bac.MLfold$results$RMSE)

#Hybrid search #################################################################
model.seq<-regsubsets(CMEDV~CRIM+ZN+INDUS+CHAS+NOX+RM+AGE+DIS+RAD+TAX+PTRATIO+B
                      +LSTAT,method="seqrep",data=boston,nvmax=15)
model.seq.s<-summary(model.seq)
model.seq.s$which

#Hybrid search stop for AIC ####################################################
out.seq=step(full,k=2,direction="both",Data=boston,trace=FALSE)
out.seq$call

#Hybrid search stop for BIC ####################################################
out.seq=step(full,k=log(506),direction="both",Data=boston,trace=FALSE)
out.seq$call

# models selected by methods ###################################################
model.for.s$which
out.forward$coefficients
model.bac.s$which
out.bac$coefficients
model.bac.MLfold$coefnames

# We see that all the methods used produce the same model, however this is not 
# a testament to each method being equal as their applications vary.

dev.off()
